import { describe, it, expect } from "vitest";
import {
  sumWeeks,
  averageWeeks,
  seasonAdot,
  seasonPacr,
  seasonRacr,
  seasonYacPerRec,
  seasonCpoe,
  seasonPassingEpa,
  seasonRushingEpa,
  seasonReceivingEpa,
} from "../stats.js";
import golden from "./golden-season-aggregates.json";

/**
 * Golden-contract test: stats.js and etl/percentiles.py implement the same
 * season-aggregation rules in two languages (JS for raw display values,
 * Python for percentile ranking). The golden file is generated by
 * etl/generate_golden.py — synthetic weeks in, Python-aggregated season
 * values out — and this suite asserts the JS helpers produce identical
 * numbers from the same weeks. If either side changes without the other,
 * this fails.
 *
 * Regenerate after contract changes:  cd etl && python generate_golden.py
 */

// metric name in the golden file → JS helper that must reproduce it
const JS_EQUIVALENTS = {
  passingEpa: (weeks) => seasonPassingEpa(weeks),
  pacr: (weeks) => seasonPacr(weeks),
  passingCpoe: (weeks) => seasonCpoe(weeks),
  passingAirYards: (weeks) => sumWeeks(weeks, "passingAirYards"),
  adot: (weeks) => seasonAdot(weeks),
  sacksSuffered: (weeks) => sumWeeks(weeks, "sacksSuffered"),
  sackYardsLost: (weeks) => sumWeeks(weeks, "sackYardsLost"),
  targetShare: (weeks) => averageWeeks(weeks, "targetShare"),
  airYardsShare: (weeks) => averageWeeks(weeks, "airYardsShare"),
  wopr: (weeks) => averageWeeks(weeks, "wopr"),
  racr: (weeks) => seasonRacr(weeks),
  receivingAirYards: (weeks) => sumWeeks(weeks, "receivingAirYards"),
  yacPerRec: (weeks) => seasonYacPerRec(weeks),
  receivingEpa: (weeks) => seasonReceivingEpa(weeks),
  rushingEpa: (weeks) => seasonRushingEpa(weeks),
  carries: (weeks) => sumWeeks(weeks, "carries"),
};

// Known, documented drift between the two implementations. Each entry is
// "<playerId>:<metric>". The test for it is declared with it.fails, so the
// suite stays green while the bug exists and goes RED the moment the JS side
// is fixed — at which point the entry must be deleted. Never add an entry
// without a note explaining the discrepancy.
//
//  - Negative season air-yard totals: percentiles.py gates PACR/RACR on
//    air yards > 0 (null otherwise, excluded from ranking); stats.js gates
//    on === 0 and returns a negative ratio. Fix: seasonPacr/seasonRacr
//    should return null when the total is <= 0.
//  - Share metrics with no non-null week: Polars mean() yields null (no
//    basis); averageWeeks returns 0, which the UI then prints as "0.0%".
//    Fix: averageWeeks should return null when nothing is averageable, and
//    its callers should format null as an em dash.
const KNOWN_DRIFT = new Set([
  "te-negative-air-yards:racr",
  "qb-negative-air-yards:pacr",
  "rb-all-null:targetShare",
  "rb-all-null:wopr",
]);

describe("stats.js mirrors the percentiles.py aggregation contract", () => {
  it("golden file covers every position the ETL ranks", () => {
    const positions = new Set(golden.players.map((p) => p.position));
    expect([...positions].sort()).toEqual(Object.keys(golden.positionConfigs).sort());
  });

  it("every ranked metric has a JS equivalent under test", () => {
    for (const config of Object.values(golden.positionConfigs)) {
      for (const metric of config.metrics) {
        expect(JS_EQUIVALENTS, metric).toHaveProperty(metric);
      }
    }
  });

  for (const player of golden.players) {
    const expected = golden.expected[player.playerId];

    describe(`${player.playerId} (${player.position})`, () => {
      for (const [metric, expectedValue] of Object.entries(expected)) {
        const declare = KNOWN_DRIFT.has(`${player.playerId}:${metric}`) ? it.fails : it;
        declare(`${metric} matches the Python aggregation`, () => {
          const actual = JS_EQUIVALENTS[metric](player.weeks);

          if (expectedValue === null) {
            // Python null means "no basis to compute" (e.g. PACR with zero
            // air yards) — the JS ratio helpers must agree with null, not 0.
            expect(actual).toBeNull();
          } else {
            expect(actual).toBeCloseTo(expectedValue, 9);
          }
        });
      }
    });
  }
});
