import { describe, it, expect } from "vitest";
import {
  sumWeeks,
  averageWeeks,
  seasonAdot,
  seasonPacr,
  seasonRacr,
  seasonYacPerRec,
  seasonCpoe,
  seasonPassingEpa,
  seasonRushingEpa,
  seasonReceivingEpa,
} from "../stats.js";
import golden from "./golden-season-aggregates.json";

/**
 * Golden-contract test: stats.js and etl/percentiles.py implement the same
 * season-aggregation rules in two languages (JS for raw display values,
 * Python for percentile ranking). The golden file is generated by
 * etl/generate_golden.py — synthetic weeks in, Python-aggregated season
 * values out — and this suite asserts the JS helpers produce identical
 * numbers from the same weeks. If either side changes without the other,
 * this fails.
 *
 * Regenerate after contract changes:  cd etl && python generate_golden.py
 */

// metric name in the golden file → JS helper that must reproduce it
const JS_EQUIVALENTS = {
  passingEpa: (weeks) => seasonPassingEpa(weeks),
  pacr: (weeks) => seasonPacr(weeks),
  passingCpoe: (weeks) => seasonCpoe(weeks),
  passingAirYards: (weeks) => sumWeeks(weeks, "passingAirYards"),
  adot: (weeks) => seasonAdot(weeks),
  sacksSuffered: (weeks) => sumWeeks(weeks, "sacksSuffered"),
  sackYardsLost: (weeks) => sumWeeks(weeks, "sackYardsLost"),
  targetShare: (weeks) => averageWeeks(weeks, "targetShare"),
  airYardsShare: (weeks) => averageWeeks(weeks, "airYardsShare"),
  wopr: (weeks) => averageWeeks(weeks, "wopr"),
  racr: (weeks) => seasonRacr(weeks),
  receivingAirYards: (weeks) => sumWeeks(weeks, "receivingAirYards"),
  yacPerRec: (weeks) => seasonYacPerRec(weeks),
  receivingEpa: (weeks) => seasonReceivingEpa(weeks),
  rushingEpa: (weeks) => seasonRushingEpa(weeks),
  carries: (weeks) => sumWeeks(weeks, "carries"),
};

describe("stats.js mirrors the percentiles.py aggregation contract", () => {
  for (const player of golden.players) {
    const expected = golden.expected[player.playerId];

    describe(`${player.playerId} (${player.position})`, () => {
      for (const [metric, expectedValue] of Object.entries(expected)) {
        it(`${metric} matches the Python aggregation`, () => {
          const actual = JS_EQUIVALENTS[metric](player.weeks);

          if (expectedValue === null) {
            // Python null means "no basis to compute" (e.g. PACR with zero
            // air yards) — the JS ratio helpers must agree with null, not 0.
            expect(actual).toBeNull();
          } else {
            expect(actual).toBeCloseTo(expectedValue, 9);
          }
        });
      }
    });
  }
});
